on:
  push:
    paths:
      - bin/strap.sh

name: 'CI'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@2.0.0
      with:
        severity: warning
